version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  centrifugo:
    build:
      context: .
      dockerfile: Dockerfile.centrifugo
    container_name: centrifugo
    ports:
      - "8000:8000"
    volumes:
      - ./config.json:/centrifugo/config.json
    environment:
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_API_KEY}
    depends_on:
      - redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    env_file: .env
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
      - centrifugo

volumes:
  postgres_data: