"""tg nullable true

Revision ID: 1fc2ef0eb454
Revises: cc4d1535bf2b
Create Date: 2025-10-27 20:50:31.093683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc2ef0eb454'
down_revision: Union[str, None] = 'cc4d1535bf2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Сначала удаляем внешние ключи из таблицы friends, если они существуют
    try:
        op.drop_constraint('friends_user_id_fkey', 'friends', type_='foreignkey')
    except:
        pass
    try:
        op.drop_constraint('friends_friend_id_fkey', 'friends', type_='foreignkey')
    except:
        pass
    
    # 2. Теперь можем удалить индекс users_tg_id_key
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    try:
        op.drop_constraint('users_tg_id_key', 'users', type_='unique')
    except:
        try:
            op.drop_index('users_tg_id_key', table_name='users')
        except:
            pass
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_unique_constraint('users_tg_id_key', 'users', ['tg_id'])
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    
    # Пересоздаем внешние ключи на tg_id
    op.create_foreign_key('friends_user_id_fkey', 'friends', 'users', ['user_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key('friends_friend_id_fkey', 'friends', 'users', ['friend_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
